version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" # Puerto 3307 en el host, 3306 dentro del contenedor
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin: # Nuevo servicio para phpMyAdmin
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_app
    restart: always
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80" 
    depends_on:
      - db 
    networks:
      - laravel

networks:
  laravel:
    external: true
    name: pomse_back_laravel 

volumes:
  dbdata: