version: '3.8'

services:
  app:
    build:
      context: .
    #dockerfile: Dockerfile
    container_name: laravel_app_https
    restart: always
    ports:
        - "8443:443"
   #volumes:
  #  - ./:/var/www/html
  #    - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
  #    - ./docker/certs:/etc/ssl 
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_app
    restart: always
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - db 
    networks:
      - laravel

networks:
  laravel:
    name: pomse_back_laravel

volumes:
  dbdata:
